### ISSUE TITLE
Not working with MUI Select and Popper

### ISSUE THREAD

**Issue by Nilesh1199** [snakesilk/react-fullscreen#100]
I'm using MUI Select and Popper, in full-screen mode if I click on select, menu list is not visible and also for the MUI Popper. As I inspected the page can see the menu list and popper being rendered (tried increasing Z-index but not working).

**Comment by pomle** [comment]
I hate to play the blame game, but this is because MUI Select don't render in the same element as the fullscreen one. As far as I know this is an implementation detail in MUI Select. 

Please see this issue for more help
https://github.com/snakesilk/react-fullscreen/issues/44

**Comment by Nilesh1199** [comment]
thanks @pomle
