### ISSUE TITLE
Back button takes user to non-enabled state

### ISSUE THREAD

**Issue by LarsLiden** [snakesilk/react-fullscreen#13]
I'm testing Fullscreen on a react app running on Android.  I capture the hardware back button for navigation purposes.  When Fullscreen is enabled the back button takes the user to the un-enabled state rather than to the previous screen.   Is there anyway to prevent this?

```
componentDidMount() {
    window.onhashchange = this.onPageNavigate
  }

  onPageNavigate() {
    if (page !== this.state.page) {
       this.setState({page}) 
    }  
  }
```

**Comment by LarsLiden** [comment]
Note this works fine on a non-phone browser such as chrome, just not on the phone browser

**Comment by pomle** [comment]
@LarsLiden unfortunately I don't believer this has anything to do with this library.
