### ISSUE TITLE
Semi transparency at the top and bottom.

### ISSUE THREAD

**Issue by LukePenkava** [snakesilk/react-fullscreen#22]
Hi,

 when my app goes fullscreen, there is slight semi transparency at the top and bottom making tabs and other things partially visible. Is there any way to make the fullscreen fully opaque ( ie no transparencey ) ?
 It is barely visible with white or black background color, but for example green or purple make it much more pronounced. The issue is very obvious with photo as background.

Thanks
Luke

**Comment by pomle** [comment]
Hi! Can you supply a screen shot or reproduction case?
