### ISSUE TITLE
ios support?

### ISSUE THREAD

**Issue by rares-lupascu** [snakesilk/react-fullscreen#23]
Hi everyone

I did not manage to get it working on any iOS browser (neither FF or Chrome)
if i remember correctly FF and Chrome should support the new fullscreen api on iOS ... safari i remember not

am i wrong?

thanks

**Comment by Neeraj-Immanent** [comment]
Hi Rares-lupascu,

Experiencing the same on my end. Couldn't able to run this on Safari Browser. Did you find any solution for this?

Thanks

**Comment by rologit85** [comment]
Hi peeps,
Same here, any new development on this. Should I look for an alternative?

Regards,

**Comment by pomle** [comment]
@rologit85, @Neeraj-Immanent, @rares-lupascu 

Hello, I haven't been able to fully investigate this, but from what I can read around on the web this is not supported on iPhone iOS. 

Looking at this package for example https://www.npmjs.com/package/screenfull it seems to suffer from the same limitations.

> Note: Safari is supported on desktop and iPad, but not on iPhone. This is a limitation in the browser, not in Screenfull.

If any of you have time to investigate I will happily implement your findings.
