### ISSUE TITLE
Is possible to Set full screen without pressing the button?

### ISSUE THREAD

**Issue by Surangaup** [snakesilk/react-fullscreen#28]
I tried for it by setting the default value to **true** in **isFull** variable. But it's not working. it returns **

> Unhandled Rejection (TypeError): fullscreen error.

**
I tried more by changing the value after some time (setTimeout()). Has any idea? I want to run the application in full screen without user pressing **F11**.

**Comment by pomle** [comment]
That is not possible due to a security limitation in the browser. Sorry for that.
