### ISSUE TITLE
Unhandled Rejection (TypeError): fullscreen error

### ISSUE THREAD

**Issue by redlive** [snakesilk/react-fullscreen#30]
When exiting fullscreen mode there is a JS error which complaints about `dispatch` hook. 

![image](https://user-images.githubusercontent.com/5912122/79497838-3d3b0700-7fdd-11ea-844d-6b1191271715.png)

**Comment by liran** [comment]
me too, same one.

**Comment by liran** [comment]
I'm going to replace it with [`fullscreen-react`](https://www.npmjs.com/package/fullscreen-react).

**Comment by pomle** [comment]
Can you please share a reproduction case?

**Comment by pomle** [comment]
I have found the problem and working on a solution.

**Comment by Nishchit14** [comment]
Our app is heavily affecting with this error, Sentry shows this error very often. any ETA on this issue? I can help in PR if you show the reference in codebase @pomle :)

**Comment by pomle** [comment]
@Nishchit14 can you try this?
https://github.com/snakesilk/react-fullscreen/issues/27#issuecomment-657026335

**Comment by pomle** [comment]
I think this is the same error as https://github.com/snakesilk/react-fullscreen/issues/27.

Closing this.
