### ISSUE TITLE
Uncaught (in promise) TypeError: fullscreen error

### ISSUE THREAD

**Issue by omersname** [snakesilk/react-fullscreen#31]
Fullscreen error only when enabled while video playing..

![image](https://user-images.githubusercontent.com/37253325/83296847-200f7000-a1fa-11ea-8e86-1076c4e91920.png)
![image](https://user-images.githubusercontent.com/37253325/83296865-29004180-a1fa-11ea-8b8e-4b22587e8d36.png)
![image](https://user-images.githubusercontent.com/37253325/83296875-2e5d8c00-a1fa-11ea-884f-1ae07e54c51f.png)

**Comment by pomle** [comment]
It is not clear from the issue how you use it.

The error suggest you are not initiating full screen mode from a user gesture.

"Fullscreen must be enabled from a user action such as `onClick`".

Let me know if this solves your problem and if you think the documentation must be improved.
