### ISSUE TITLE
Not working on mobile

### ISSUE THREAD

**Issue by BoazKG93** [snakesilk/react-fullscreen#37]
When i try and use it on mobile browsers (Safari, Chrome, Firefox) it won't work. On desktop it works fine.

**Comment by qnts** [comment]
I also encountered the same behavior.

**Comment by qnts** [comment]
requestFullscreen is not available on iOS mobile devices, on ipad it works however. For android devices this still works.

**Comment by blixit** [comment]
Hello,

As you can see in the picture, and as @qnts said, fscreen returns an empty vendor for iOS devices.

Is it possible to you guys to implement a try-catch pattern to catch this bug ?

![image](https://user-images.githubusercontent.com/6025710/102012729-69657e00-3d4c-11eb-8e96-e5aba3126a60.png)

**Comment by pomle** [comment]
@blixit, thank you for the report. 

What I had in mind was that I can expose the promise so that you can catch the error from there. That way the implementer can treat this error like they think is best.

For your case it would be 

```js
handle.enter().catch(error => {
// do something with error for example setFullScreenError(error)
});
```

Let me know if this would work for you.

Thanks!

**Comment by blixit** [comment]
hi @pomle and sorry for the delay. Yeah this way could help. thanks !

**Comment by pomle** [comment]
@blixit cool. Check this issue for details on how to proceed https://github.com/snakesilk/react-fullscreen/issues/48

**Comment by beandip004** [comment]
Hi @pomle, do you plan to make this work for iPhone users?
(Sorry I'm a n00b, but I'm not sure why this is closed if it's still an issue)

**Comment by AmmRage** [comment]
> Hi @pomle, do you plan to make this work for iPhone users? (Sorry I'm a n00b, but I'm not sure why this is closed if it's still an issue)

because  it's up to Apple officially do not allow.
