### ISSUE TITLE
Unable to scroll in full screen mode

### ISSUE THREAD

**Issue by jsevedge** [snakesilk/react-fullscreen#42]
Hey, this plugin is super useful first off.  Secondly, is it expected that overflow content cannot be scrolled when in full screen mode?  I know that not allowing scrolling used to be part of the full screen spec but that has since changed iirc.

**Comment by pomle** [comment]
That is not expected and nothing this component should care about.

If you have a case to reproduce your problem and expectation I can have a look and see if I can figure something out. 

A guess is that perhaps the element that is full screen will not scroll. In that case you should be able to put a scrollable element inside it to adress that.
