### ISSUE TITLE
Impossible to deploy in Class Component

### ISSUE THREAD

**Issue by codeyourweb** [snakesilk/react-fullscreen#45]
-- react-full-screen@0.3.1

Hi,

i follow your README but i've got when my React application start:
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem. 

I'm really new to React.js; before posting an issue here, i checked some information to solve my problem but it seems i can't solve it.
- it seems that there isn't react/reactdom mismatch (react@16.13.1 / react-dom@16.13.1)
- i only have one copy of react in the same app
- i didn't really understood what React documentation said on Rules of Hooks but maybe this issue is related with the fact i use Class Component instead of function. Here's a partial copy of the class where i would like to use react-full-screen. Any help would be appeciatedd 

```
import React, {useCallback}  from 'react';
import { FullScreen, useFullScreenHandle } from 'react-full-screen';


export default class Investigation extends React.Component {
	render(){
		const fsHandle = useFullScreenHandle();

		return (
			<div>
				<FullScreen handle={fsHandle}>
					<div id="investigation-fullscreen">
						<ul className="list-inline pull-right">
							<li className="list-inline-item"><a onClick={ this.arrangeItems.bind(this) } className="btn btn-default"><i className="fa fa-certificate"></i></a></li>
							<li className="list-inline-item"><a onClick={ this.centerView.bind(this) } className="btn btn-default"><i className="fa fa-street-view"></i></a></li>
							<li className="list-inline-item"><a onClick={fsHandle.enter} className="btn btn-default"><i className="fa fa-expand"></i></a></li>
						</ul>	
					</div>
					<div id="search-box">
					<input type="text" className="form-control search-control" placeholder="Search any element (Report, Indicator, Signature...)"/>				
					</div>
					<div id="investigation-content">
						<CytoscapeComponent cy={(cy) => { this.cy = cy }} layout={layout} minZoom={0.5} maxZoom={3} elements={elements} style={ { height:'80vh', width: '90vw', padding: '10px' } } />
					</div>
				</FullScreen>
			</div>
		);
	}
}
```

**Comment by pomle** [comment]
The 0.3.x is only compatible with hooks which is only compatible with functional components.

If you must use class component you can use 0.2.5 https://www.npmjs.com/package/react-full-screen/v/0.2.5 but it has drawbacks which makes it hard to have many full screen elements in the same page.
