### ISSUE TITLE
Issue Migrating to v0.3.x

### ISSUE THREAD

**Issue by joncursi** [snakesilk/react-fullscreen#46]
I'm on version `0.2.x` and trying to upgrade to version `0.3.x`, and not sure how to work with the `handle`.

In the README.md example, `Fullscreen` is inside the same component as the `button` used to invoke it.

```jsx
import React, {useCallback} from 'react';
import { FullScreen, useFullScreenHandle } from "react-full-screen";

function App() {
  const handle = useFullScreenHandle();

  return (
    <div>
      <button onClick={handle.enter}>
        Enter fullscreen
      </button>

      <FullScreen handle={handle}>
        Any fullscreen content here
      </FullScreen>
    </div>
  );
}

export default App;
```

Easy peasy.

However, more complex apps like mine have the `button` very far away from `Fullscreen` in terms of the react tree... not in the same component. So how do we share the `handle` between `Fullscreen` and the button(s) used to invoke it?

**Comment by pomle** [comment]
Thank you for this interesting new problem space I have not thought about.

The first idea that comes to mind is passing the handle down to the Fullscreen element. If that becomes cumbersome, maybe you can build something to pass down the handle using [React Context](https://reactjs.org/docs/context.html)

Let me know if this solves the problem or if there are concerns that I may be able to help address further.

**Comment by pomle** [comment]
Closing due to inactivitly.
