### ISSUE TITLE
custom styles/ classname

### ISSUE THREAD

**Issue by israelKusayev** [snakesilk/react-fullscreen#57]
Can you add the ability to forward a classname/styles to the wrapper div?

Thanks

**Comment by pomle** [comment]
Yes, let's do this.

Will attend https://github.com/snakesilk/react-fullscreen/pull/43 in a few days.

**Comment by pomle** [comment]
@israelKusayev I attended it now. Released 1.0.0 with class name injection support and Promise return https://github.com/snakesilk/react-fullscreen/issues/48
