### ISSUE TITLE
Support for react >= 17

### ISSUE THREAD

**Issue by MrShtrahman** [snakesilk/react-fullscreen#60]
Hi,
will support for react 17.0.0 (or above) be considered in the future? (as a peer-dep)
Thanks 😄

**Comment by pomle** [comment]
@MrShtrahman hey, thanks for pointing that out. Definitely. Will look into it first free time I get.

**Comment by pomle** [comment]
@MrShtrahman from 0.1.2 React peer dep is defined as >= 16.8

Thank you
