### ISSUE TITLE
Not working on iOS Safari or iOS Chrome

### ISSUE THREAD

**Issue by svargas-dev** [snakesilk/react-fullscreen#64]
Works fine on desktop Chrome / Firefox but not on iOS Safari or iOS Chrome

**Comment by svargas-dev** [comment]
Scrap that. I see the fullscreen API isn't supported by iPhones.

**Comment by skoal2007** [comment]
Hi Svargas, any work around for this issue. I also notice this package not working on iphone iOS.

**Comment by asierba-air-up** [comment]
hi, any update or work around for this?

**Comment by kr-viku** [comment]
**Not working on ios mobile devices.**
_Getting this error:_ 
`element[vendor[key.requestFullscreen]] is not a function. (In 'element[vendor[key.requestFullscreen]]()', 'element[vendor[key.requestFullscreen]]' is undefined)`

**Comment by adon988** [comment]
Issue still on:
```
TypeError: element[vendor[key.requestFullscreen]] is not a function. (In 'element[vendor[key.requestFullscreen]]()', 'element[vendor[key.requestFullscreen]]' is undefined)
```

**Comment by felipedeboni** [comment]
iOS only supports it on iPad, however I think this hook could detect that and portal the content and add a class to it so it will at least mimic the behavior of a fullscreen instead of throwing errors.

Sadly I don't have time right now to make a PR, will implement in a scrappy way.
