### ISSUE TITLE
I'm getting an error in my console

### ISSUE THREAD

**Issue by DCStudioProjects** [snakesilk/react-fullscreen#66]
I'm getting an error in my console.
Error:
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

**Comment by pomle** [comment]
Please provide example and reopen.

**Comment by DCStudioProjects** [comment]
Hello, here is an example:
DEMO: https://logqz.csb.app/
CodeSandbox: https://codesandbox.io/s/gallant-hoover-logqz?file=/src/App.js

**Comment by pomle** [comment]
Hello!

This is not an issue with this library. But you can access the DOM Node ref via the `node` prop on the handle as described here: https://github.com/snakesilk/react-fullscreen#types
