### ISSUE TITLE
"requestFullscreen is not a function" in safari iOS

### ISSUE THREAD

**Issue by lapanton** [snakesilk/react-fullscreen#69]
Hi! Guys, as i see is safari in ios you have a bug (((( Do you have any fix, or workaround for it? 
![Screenshot 2021-07-16 at 09 23 59](https://user-images.githubusercontent.com/16897033/125902019-72c36117-f0be-4c6a-a261-bec0df6e79ab.png)

**Comment by pomle** [comment]
See https://github.com/snakesilk/react-fullscreen/issues/64
