### ISSUE TITLE
Crash after exit fullscreen | "Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by SunD004** [snakesilk/react-fullscreen#79]
I have this crash sometimes when i exit the fullscreen mode

![Screenshot from 2022-01-12 17-51-59](https://user-images.githubusercontent.com/44288530/149185237-48533218-ecf4-4a84-ad0e-fb4e70f72d4a.png)

**Comment by pomle** [comment]
@SunD004 that is unrelated. The code crashing it not part of this library. I suggest you look into if you have any toast lib that you are using that manipulates the DOM outside React.

**Comment by SunD004** [comment]
> @SunD004 that is unrelated. The code crashing it not part of this library. I suggest you look into if you have any toast lib that you are using that manipulates the DOM outside React.

Yes effectively

For people who have this crash because full screen and react-toastify just place <ToastContainer/> in App.js and it will fix the crash of searching in DOM NotFound

`import { ToastContainer } from "react-toastify";

  <ToastContainer />
`
