### ISSUE TITLE
Add support to React v18

### ISSUE THREAD

**Issue by VikaCep** [snakesilk/react-fullscreen#85]
In order to use this library with React 18+, the children prop now [needs to be listed explicitly when defining props](https://github.com/snakesilk/react-fullscreen/blob/master/src/index.tsx#L17). Otherwise the `Fullscreen` component can't be used in this version.

**Comment by hcharley** [comment]
Running up against this now as well. Will solve with a quick and dirty trick:

```tax
  const FullScreenComp = FullScreen as any;
```

**Comment by israel-lpz** [comment]
The same for mi

![image](https://user-images.githubusercontent.com/74976929/163869863-dc7ee897-52e7-4105-a996-f9918f35c686.png)

**Comment by pomle** [comment]
Thank you, I will look into this as soon as possible.

**Comment by weynelucas** [comment]
> Running up against this now as well. Will solve with a quick and dirty trick:
> 
> ```
>   const FullScreenComp = FullScreen as any;
> ```

To deal with `@typescript-eslint/no-explicit-any` ESLint rule:

```tsx
import React from 'react';
import { FullScreen, FullScreenProps } from 'react-full-screen';

const FullScreenWithChildren = FullScreen as React.FC<React.PropsWithChildren<FullScreenProps>>
```
