### ISSUE TITLE
Shows black screen on full screen

### ISSUE THREAD

**Issue by kachrist001** [snakesilk/react-fullscreen#86]
After executing the sample code, it showed black screen in full screen with all browsers.
It works fine with clicking F11 button.

  "dependencies": {
    "next": "12.1.5",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-full-screen": "^1.1.0"
  },
  "devDependencies": {
    "eslint": "8.13.0",
    "eslint-config-next": "12.1.5"
  }

**Comment by pomle** [comment]
Thanks, I will look into this as soon as I have a chance.

**Comment by mhsu0020** [comment]
I think the default background color for the overlay is black. You can that in your CSS

```
.fullscreen-enabled .your-component {
  background: green;
}
```

**Comment by anixudh** [comment]
Changing the background color to white in CSS fixed this issue

**Comment by Ivan-Corporation** [comment]
if you need turn off fullscreen default black color you can just rewrite it in your root styles file like this:
`
:fullscreen::backdrop {
 background:none
}`
